export class RegistroDatosPersonalesDTO{
  numeroDeIdentificacion:string;
  nombre: string;
  nombre_modificado:boolean;
  apellido: string;
  apellido_modificado:boolean;
  apodo: string;
  apodo_modificado:boolean;
  estadoCivil: number;
  estadoCivil_modificado:boolean;
  fechaNacimiento: Date;
  fechaNacimiento_modificado:boolean;
  nacionalidad: number;
  nacionalidad_modificado:boolean;
  lugarDeNacimiento: string;
  lugarDeNacimiento_modificado:boolean;
  sexo: string;
  sexo_modificado:boolean;
  tipoDeDocumento: string;
  tipoDeDocumento_modificado:boolean;
  numeroDocumento: string;
  numeroDocumento_modificado:boolean;
  direccion: string;
  direccion_modificado:boolean;
  barrio: string;
  barrio_modificado:boolean;
  compania: string;
  compania_modificado:boolean;
  numeroDeContacto: string;
  numeroDeContacto_modificado:boolean;
  contactoDeEmergencia1: string;
  contactoDeEmergencia1_modificado:boolean;
  contactoDeEmergencia2: string;
  contactoDeEmergencia2_modificado:boolean;
  pueblosIndigenas: boolean;
  pueblosIndigenas_modificado:boolean;
  nombreEtnia: string;
  nombreEtnia_modificado:boolean;
  perteneceAComunidadLGTBI:boolean;
  perteneceAComunidadLGTBI_modificado:boolean;
  grupoLgbti: string;
  grupoLgbti_modificado:boolean;
}