apiVersion: v1
kind: PersistentVolume
metadata:
  name: archivos-identifacil
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/identifacil/archivos"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: archivos-identifacil
  name: archivos-identifacil-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi