apiVersion: v1
kind: PersistentVolume
metadata:
  name: registro-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/registro"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: registro-data
  name: registro-data-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
